"""Runtime loop that hydrates a surface map from configured connectors.

Called from :mod:`blanc.core.threat_modeling` just before the LLM
prompt is built, so every threat generated by the model sees the
enriched fields.

Concurrency model
-----------------
For each ``target`` in ``field_sources`` we fan out over the target's
entities (components or boundaries) concurrently. Within one entity,
the fallback chain runs sequentially — first non-null wins.

If any connector raises, we log and continue to the next in the chain.
No single upstream can break the whole hydration.
"""
from __future__ import annotations

import asyncio
import logging
from typing import Dict, List

from blanc.core.integrations.base import ConnectorResult, SurfaceMapConnector
from blanc.core.integrations.db_helpers import clear_context, set_context
from blanc.core.integrations.http_runner import (
    CircuitOpenError, HostNotAllowed,
)
from blanc.schemas.surface_map import SurfaceMapPayload

logger = logging.getLogger(__name__)


class Dispatcher:
    def __init__(
        self,
        connectors_by_name: Dict[str, SurfaceMapConnector],
        field_sources: Dict[str, List[str]],
    ):
        self._connectors = connectors_by_name
        self._field_sources = field_sources

    async def hydrate(
        self,
        surface_map: SurfaceMapPayload,
        *,
        assessment_id: str,
        image_id: str,
    ) -> None:
        """Populate every field listed in ``field_sources``.

        Writes happen via :func:`update_surface_field`, which reads
        ``(assessment_id, image_id)`` from a ContextVar — so we set it
        once here and don't have to thread it through every method.
        """
        set_context(assessment_id, image_id)
        try:
            tasks = []
            for target, chain in self._field_sources.items():
                if not chain:
                    continue
                kind = target.split(".", 1)[0]
                if kind == "component":
                    entities = surface_map.components
                elif kind == "boundary":
                    entities = surface_map.trust_boundaries
                else:
                    logger.warning(
                        "[%s] unknown target kind %r in field_sources (target=%s)",
                        assessment_id, kind, target,
                    )
                    continue

                for entity in entities:
                    tasks.append(self._run_chain(
                        target, chain, entity, assessment_id,
                    ))

            if not tasks:
                logger.debug(
                    "[%s] no field_sources configured — nothing to hydrate",
                    assessment_id,
                )
                return

            # ``return_exceptions=True`` — a single connector blowing up
            # must not cancel the sibling tasks that were also fanned
            # out. Failures are already logged inside ``_run_chain``.
            await asyncio.gather(*tasks, return_exceptions=True)
        finally:
            clear_context()

    # ── internals ─────────────────────────────────────────────────
    async def _run_chain(
        self, target: str, chain: List[str], entity, assessment_id: str,
    ) -> None:
        for class_name in chain:
            conn = self._connectors.get(class_name)
            if conn is None:
                logger.warning(
                    "[%s] field_sources[%s] references unknown connector %r",
                    assessment_id, target, class_name,
                )
                continue
            if target not in conn.supported_targets:
                logger.warning(
                    "[%s] connector %s does not support target %s — skipping",
                    assessment_id, class_name, target,
                )
                continue

            try:
                result = await self._try_one(conn, entity, target)
            except (CircuitOpenError, HostNotAllowed) as e:
                logger.warning(
                    "[%s] %s / %s / %s — skipped: %s",
                    assessment_id, class_name, entity.name, target, e,
                )
                continue
            except Exception:
                logger.exception(
                    "[%s] %s failed for %s / %s — falling back",
                    assessment_id, class_name, entity.name, target,
                )
                continue

            if result is None:
                # Connector answered but had nothing usable → next in chain.
                continue

            try:
                await conn.db_operations(result, entity, target)
            except Exception:
                logger.exception(
                    "[%s] %s db_operations failed for %s / %s",
                    assessment_id, class_name, entity.name, target,
                )
                continue

            return  # first non-null result wins

    @staticmethod
    async def _try_one(
        conn: SurfaceMapConnector, entity, target: str,
    ) -> ConnectorResult | None:
        for request in conn.get_api_calls(entity, target):
            response = await conn.http.send(request)
            result = conn.parse_response(response, entity, target)
            if result is not None:
                return result
        return None


__all__ = ["Dispatcher"]
